config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'pages#index'
  get '/about-me', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :posts

  namespace :dashboard do
    resources :books
    resources :posts
    resources :users
    resources :categories
  end

  scope module: 'api' do
    namespace :v1, defaults: { format: :json } do
      get '/reading', to: 'books#index'
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, :progress, :start, :comment, :image, presence: true
end

app/controllers/api/v1/books_controller.rb
module Api
  module V1
    class BooksController < ActionController::Base
      def index
        render json: Book.all.order('created_at DESC'), status: :ok
      end
    end
  end
end

app/controllers/dashboard/books_controller.rb
module Dashboard
  class BooksController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def index
      @books = Book.all
    end

    def show
    end

    def new
      @book = Book.new
    end

    def edit
    end

    def create
      @book = Book.new(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to dashboard_book_path(@book), notice: 'Book was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to dashboard_book_path(@book), notice: 'Book was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @book.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_book
        @book = Book.find(params[:id])
      end

      def book_params
        params.require(:book).permit(:title, :author, :progress, :start, :comment, :image)
      end
  end
end

app/controllers/dashboard/categories_controller.rb
module Dashboard
  class CategoriesController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
    end

    def show;end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to dashboard_categories_path, notice: 'Category created'
      else
        render :new
      end
    end

    def edit;end

    def update
      if @category.update(category_params)
        redirect_to dashboard_category_path(@category), notice: 'Category created'
      else
        render :new
      end
    end

    def destroy
      if @category.destroy
        redirect_to dashboard_categories_path, notice: 'Category deleted'
      end
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/dashboard/posts_controller.rb
module Dashboard
  class PostsController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all.order('created_at DESC')
    end

    def show
    end

    def new
      @post = Post.new
      @categories = Category.all
    end

    def edit
      @categories = Category.all
    end

    def create
      @post = Post.new(post_params)
      respond_to do |format|
        if @post.save
          format.html { redirect_to dashboard_posts_path(@post), notice: 'Post was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to edit_dashboard_post_path(@post), notice: 'Post was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_posts_path, notice: 'Post was successfully deleted.' }
      end
    end

    private
      def set_post
        @post = Post.friendly.find(params[:id]).decorate
      end

      def post_params
        params.require(:post).permit(:title, :category_id, :subtitle, :body, :published, :published_at)
      end
  end
end

app/controllers/dashboard/users_controller.rb
module Dashboard
  class UsersController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end

    def show
    end

    def new
      @user = User.new
    end

    def edit
    end

    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to dashboard_user_path(@user), notice: 'User was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to dashboard_user_path(@user), notice: 'User was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
  end
end

app/views/dashboard/books/_form.html.erb
<%= form.submit class: "btn btn-primary" %>

<% if book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

    <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group" style="margin-top: 40px;">
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :author %>
  <%= form.text_field :author, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :start %>
  <%= form.text_field :start, class: "form-control", rows: 20 %>
</div>

<div class="form-group">
  <%= form.label :progress %>
  <%= form.text_field :progress, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :comment %>
  <%= form.text_area :comment, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :image %>
  <%= form.text_field :image, class: "form-control" %>
</div>

<%= form.submit class: "btn btn-primary", style: "margin-bottom: 40px;" %>

app/views/dashboard/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'dashboard/shared/notifications' %>

<span class="float-right"><%= link_to 'Show', dashboard_book_path(@book), class: "btn btn-primary" %></span>

<%= form_with(model: @book, url: dashboard_book_path(@book), local: true) do |form| %>
  <%= render 'form', book: @book, form: form %>
<% end %>

app/views/dashboard/books/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Books</h1>
<%= render 'dashboard/shared/notifications' %>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Filters</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <% if @books.present? %>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Title</th>
              <th>Author</th>
              <th>Progress</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td><%= book.title %></td>
                <td><%= book.author %></td>
                <td><%= book.progress %></td>
                <td>
                  <%= link_to dashboard_book_path(book) do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                  <%= link_to edit_dashboard_book_path(book) do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to dashboard_book_path(book), method: :delete, data: { confirm: 'Delete book?' } do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No books have been posted yet. </p>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/books/new.html.erb
<h1 class="h3 mb-2 text-gray-800">New Book</h1>

<%= render 'dashboard/components/notices'  %>

<%= form_with(model: @book, url: dashboard_books_path, local: true) do |form| %>
  <%= render 'form', book: @book, form: form %>
<% end %>

app/views/dashboard/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-group">
  <%= link_to 'Edit', edit_dashboard_book_path(@book), class: "btn btn-primary" %>
</div>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Start:</strong>
  <%= @book.start %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @book.progress %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @book.comment %>
</p>

<p><strong>Image:</strong></p>
<%= image_tag(@book.image) %>