config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'pages#index'
  get '/about-me', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :posts

  namespace :dashboard do
    resources :books
    resources :posts
    resources :users
    resources :categories
  end

  scope module: 'api' do
    namespace :v1, defaults: { format: :json } do
      get '/reading', to: 'books#index'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :category

  before_save :define_published_at

  validates :title, :body, presence: true

  scope :all_published, -> { where(published: true).order('created_at DESC') }
  scope :home,  -> { where(published: true).order('created_at DESC').limit(5) }

  private

  def define_published_at
    unless self.published_at.present?
      self.published_at = self.published ? Date.today : nil
    end
  end
end

app/controllers/dashboard/books_controller.rb
module Dashboard
  class BooksController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def index
      @books = Book.all
    end

    def show
    end

    def new
      @book = Book.new
    end

    def edit
    end

    def create
      @book = Book.new(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to dashboard_book_path(@book), notice: 'Book was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to dashboard_book_path(@book), notice: 'Book was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @book.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_book
        @book = Book.find(params[:id])
      end

      def book_params
        params.require(:book).permit(:title, :author, :progress, :start, :comment, :image)
      end
  end
end

app/controllers/dashboard/categories_controller.rb
module Dashboard
  class CategoriesController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
    end

    def show;end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to dashboard_categories_path, notice: 'Category created'
      else
        render :new
      end
    end

    def edit;end

    def update
      if @category.update(category_params)
        redirect_to dashboard_category_path(@category), notice: 'Category created'
      else
        render :new
      end
    end

    def destroy
      if @category.destroy
        redirect_to dashboard_categories_path, notice: 'Category deleted'
      end
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/dashboard/posts_controller.rb
module Dashboard
  class PostsController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all.order('created_at DESC')
    end

    def show
    end

    def new
      @post = Post.new
      @categories = Category.all
    end

    def edit
      @categories = Category.all
    end

    def create
      @post = Post.new(post_params)
      respond_to do |format|
        if @post.save
          format.html { redirect_to dashboard_posts_path(@post), notice: 'Post was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to edit_dashboard_post_path(@post), notice: 'Post was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_posts_path, notice: 'Post was successfully deleted.' }
      end
    end

    private
      def set_post
        @post = Post.friendly.find(params[:id]).decorate
      end

      def post_params
        params.require(:post).permit(:title, :category_id, :subtitle, :body, :published, :published_at)
      end
  end
end

app/controllers/dashboard/users_controller.rb
module Dashboard
  class UsersController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end

    def show
    end

    def new
      @user = User.new
    end

    def edit
    end

    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to dashboard_user_path(@user), notice: 'User was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to dashboard_user_path(@user), notice: 'User was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:show]

  def index
    @posts = Post.all.order('CREATED_AT DESC')
  end

  def show
  end

  private

  def find_post
    @post = Post.find_by(slug: params[:id])
  end
end

app/views/dashboard/posts/_form.html.erb
<%= form.submit class: "btn btn-primary" %>

<% if post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group" style="margin-top: 40px;">
  <%= form.label :title %>
  <%= form.text_field :title, class: "form-control" %>
</div>

<div class="form-group" style="margin-top: 40px;">
  <%= form.label :subtitle %>
  <%= form.text_field :subtitle, class: "form-control" %>
</div>

<div class="form-group" style="margin-top: 40px;">
  <%= form.label :category %>
  <%= form.select :category_id, Category.all.collect { |category| [category.name, category.id] }, {:selected_value => @post.category.try(:id) || nil}, { class: "form-control" } %>
</div>

<div class="form-group">
  <%= form.label :slug %>
  <%= form.text_field :slug, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :body %>
  <%= form.text_area :body, class: "form-control", rows: 50 %>
</div>

<div class="form-group">
  <%= form.label :published_at %>
  <%= form.date_field :published_at, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :published %>
  <%= form.check_box :published, class: "form-control" %>
</div>

<%= form.submit class: "btn btn-primary", style: "margin-bottom: 40px;" %>

app/views/dashboard/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'dashboard/shared/notifications' %>

<span class="float-right"><%= link_to 'Show', dashboard_post_path(@post), class: "btn btn-primary" %></span>

<%= form_with(model: @post, url: dashboard_post_path(@post), local: true) do |form| %>
  <%= render 'form', post: @post, form: form %>
<% end %>

app/views/dashboard/posts/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Posts</h1>
<%= render 'dashboard/shared/notifications' %>

<!-- DataTales Example -->
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">Filters</h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <% if @posts.present? %>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Title</th>
              <th>Created at</th>
              <th>Updated at</th>
              <th>Published at</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tfoot>
            <tr>
              <th>Title</th>
              <th>Created at</th>
              <th>Updated at</th>
              <th>Published at</th>
              <th>Actions</th>
            </tr>
          </tfoot>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= post.title %></td>
                <td><%= post.created_at %></td>
                <td><%= post.updated_at %></td>
                <td><%= post.published_at %></td>
                <td>
                  <%= link_to dashboard_post_path(post) do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                  <%= link_to edit_dashboard_post_path(post) do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to dashboard_post_path(post), method: :delete, data: { confirm: 'Delete post?' } do %>
                    <i class="fas fa-trash"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No posts have been posted yet. </p>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/posts/new.html.erb
<h1 class="h3 mb-2 text-gray-800">New Post</h1>

<%= render 'dashboard/components/notices'  %>

<%= form_with(model: @post, url: dashboard_posts_path, local: true) do |form| %>
  <%= render 'form', post: @post, form: form %>
<% end %>

app/views/dashboard/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-group">
  <%= link_to 'Edit', edit_dashboard_post_path(@post), class: "btn btn-primary" %>
</div>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @post.slug %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.markdown %>
</p>

<p>
  <strong>Published:</strong>
  <%= @post.published %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @post.published_at %>
</p>