config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login',  to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'pages#index'
  get '/about-me', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :posts

  namespace :dashboard do
    resources :books
    resources :posts
    resources :users
    resources :categories
  end

  scope module: 'api' do
    namespace :v1, defaults: { format: :json } do
      get '/reading', to: 'books#index'
    end
  end
end

app/controllers/dashboard/books_controller.rb
module Dashboard
  class BooksController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_book, only: [:show, :edit, :update, :destroy]

    def index
      @books = Book.all
    end

    def show
    end

    def new
      @book = Book.new
    end

    def edit
    end

    def create
      @book = Book.new(book_params)

      respond_to do |format|
        if @book.save
          format.html { redirect_to dashboard_book_path(@book), notice: 'Book was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @book.update(book_params)
          format.html { redirect_to dashboard_book_path(@book), notice: 'Book was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @book.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_book
        @book = Book.find(params[:id])
      end

      def book_params
        params.require(:book).permit(:title, :author, :progress, :start, :comment, :image)
      end
  end
end

app/controllers/dashboard/categories_controller.rb
module Dashboard
  class CategoriesController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_category, only: [:show, :edit, :update, :destroy]

    def index
      @categories = Category.all
    end

    def show;end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to dashboard_categories_path, notice: 'Category created'
      else
        render :new
      end
    end

    def edit;end

    def update
      if @category.update(category_params)
        redirect_to dashboard_category_path(@category), notice: 'Category created'
      else
        render :new
      end
    end

    def destroy
      if @category.destroy
        redirect_to dashboard_categories_path, notice: 'Category deleted'
      end
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
  end
end

app/controllers/dashboard/posts_controller.rb
module Dashboard
  class PostsController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def index
      @posts = Post.all.order('created_at DESC')
    end

    def show
    end

    def new
      @post = Post.new
      @categories = Category.all
    end

    def edit
      @categories = Category.all
    end

    def create
      @post = Post.new(post_params)
      respond_to do |format|
        if @post.save
          format.html { redirect_to dashboard_posts_path(@post), notice: 'Post was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to edit_dashboard_post_path(@post), notice: 'Post was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @post.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_posts_path, notice: 'Post was successfully deleted.' }
      end
    end

    private
      def set_post
        @post = Post.friendly.find(params[:id]).decorate
      end

      def post_params
        params.require(:post).permit(:title, :category_id, :subtitle, :body, :published, :published_at)
      end
  end
end

app/controllers/dashboard/users_controller.rb
module Dashboard
  class UsersController < ApplicationController

    layout 'dashboard'

    before_action :authorize
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end

    def show
    end

    def new
      @user = User.new
    end

    def edit
    end

    def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to dashboard_user_path(@user), notice: 'User was successfully created.' }
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to dashboard_user_path(@user), notice: 'User was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to dashboard_users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
      end
  end
end

app/views/dashboard/components/_notices.html.erb
<p class="mb-4">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</p>

app/views/dashboard/components/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="/dashboard/books">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">AJr.</div>
  </a>

  <hr class="sidebar-divider">

  <li class="nav-item <%= 'active' if params[:action] == 'index' && params[:controller] == 'dashboard/categories' %> ">
    <a class="nav-link" href="<%= url_for(dashboard_categories_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Categories</span></a>
  </li>

  <li class="nav-item <%= 'active' if params[:action] == 'new' && params[:controller] == 'dashboard/categories' %> ">
    <a class="nav-link" href="<%= url_for(new_dashboard_category_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>New Category</span></a>
  </li>

  <hr class="sidebar-divider">

  <li class="nav-item <%= 'active' if params[:action] == 'index' && params[:controller] == 'dashboard/posts' %> ">
    <a class="nav-link" href="<%= url_for(dashboard_posts_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Posts</span></a>
  </li>

  <li class="nav-item <%= 'active' if params[:action] == 'new' && params[:controller] == 'dashboard/posts' %> ">
    <a class="nav-link" href="<%= url_for(new_dashboard_post_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>New Post</span></a>
  </li>

  <hr class="sidebar-divider">

  <li class="nav-item <%= 'active' if params[:action] == 'index' && params[:controller] == 'dashboard/books' %> ">
    <a class="nav-link" href="<%= url_for(dashboard_books_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>List Books</span></a>
  </li>

  <li class="nav-item <%= 'active' if params[:action] == 'new' && params[:controller] == 'dashboard/books' %> ">
    <a class="nav-link" href="<%= url_for(new_dashboard_book_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>New Book</span></a>
  </li>

  <hr class="sidebar-divider">

  <div class="sidebar-heading">
    Users
  </div>

  <li class="nav-item <%= 'active' if params[:action] == 'index' && params[:controller] == 'dashboard/users' %> ">
    <a class="nav-link" href="<%= url_for(dashboard_users_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Users</span></a>
  </li>

  <li class="nav-item <%= 'active' if params[:action] == 'new' && params[:controller] == 'dashboard/users' %> ">
    <a class="nav-link" href="<%= url_for(new_dashboard_user_path) %>">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>New User</span></a>
  </li>

  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/views/dashboard/components/_topbar.html.erb
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

<!-- Sidebar Toggle (Topbar) -->
<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
<i class="fa fa-bars"></i>
</button>

<!-- Topbar Search -->
<!-- <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
<div class="input-group">
    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
    <div class="input-group-append">
    <button class="btn btn-primary" type="button">
        <i class="fas fa-search fa-sm"></i>
    </button>
    </div>
</div>
</form> -->

<!-- Topbar Navbar -->
<ul class="navbar-nav ml-auto">

<!-- Nav Item - Search Dropdown (Visible Only XS) -->
<li class="nav-item dropdown no-arrow d-sm-none">
    <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="fas fa-search fa-fw"></i>
    </a>
    <!-- Dropdown - Messages -->
    <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
    <form class="form-inline mr-auto w-100 navbar-search">
        <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-primary" type="button">
            <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
        </div>
    </form>
    </div>
</li>

<div class="topbar-divider d-none d-sm-block"></div>

<!-- Nav Item - User Information -->
<li class="nav-item dropdown no-arrow">
    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <% if current_user %>
      <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.email %></span>
    <% end %>
    </a>
    <!-- Dropdown - User Information -->
    <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
    <a class="dropdown-item" href="#">
        <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
        Profile
    </a>
    <a class="dropdown-item" href="#">
        <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
        Settings
    </a>
    <a class="dropdown-item" href="#">
        <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
        Activity Log
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="<%= url_for(logout_path) %>">
        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
        Logout
    </a>
    </div>
</li>

</ul>

</nav>
<!-- End of Topbar -->